import {
    FaHome,
    FaShoppingCart,
    FaUserFriends,
    FaMoneyCheckAlt,
    FaBell,
    FaThLarge,
    FaBoxOpen,
    FaTruck,
    FaUsersCog,
    FaMapMarkerAlt,
    FaExchangeAlt,
    FaChartLine,
    FaHandshake,
    FaInbox,
    FaTags,
    FaPaintBrush,
    FaFileInvoiceDollar,
    FaCogs,
    FaPuzzlePiece,
    FaRocket,
    FaFileContract,
    FaInfoCircle,
    FaPhoneAlt,
    FaLifeRing,
    FaCaretSquareDown,
    FaSitemap,
    FaCamera,
} from 'react-icons/fa';
import { FiMessageSquare } from 'react-icons/fi';

export const ADMIN_SIDEBAR_LINKS = [
    {
        key: 'dashboard',
        label: 'Dashboard',
        href: '/admin',
        icon: <FaHome />,
    },
    {
        key: 'orders',
        label: 'Orders',
        href: '/admin/orders',
        icon: <FaShoppingCart />,
    },
    {
        key: 'queries',
        label: 'Queries',
        href: '/admin/queries',
        icon: <FiMessageSquare />,
    },
    {
        key: 'categories',
        label: 'Categories',
        href: '/admin/categories',
        icon: <FaThLarge />,
    },
    {
        key: 'subCategories',
        label: 'Sub Categories',
        href: '/admin/subCategories',
        icon: <FaSitemap />,
    },
    {
        key: 'products',
        label: 'Products',
        href: '/admin/products',
        icon: <FaBoxOpen />,
    },
    {
        key: 'groups',
        label: 'Product Groups',
        href: '/admin/groups',
        icon: <FaCaretSquareDown />,
    },
    {
        key: 'design-studio',
        label: 'Design Studio',
        href: '/admin/design-studio',
        icon: <FaCamera />,
    },
    {
        key: 'media',
        label: 'Media',
        href: '/admin/media',
        icon: <FaPaintBrush />,
    },
    {
        key: 'customers',
        label: 'Customers',
        href: '/admin/customers',
        icon: <FaUserFriends />,
    },
    {
        key: 'employees',
        label: 'Employees',
        href: '/admin/employees',
        icon: <FaUsersCog />,
    },
    {
        key: 'notifications',
        label: 'Notifications',
        href: '/admin/notifications',
        icon: <FaBell />,
    },
    {
        key: 'reports',
        label: 'Reports',
        href: '/admin/reports',
        icon: <FaChartLine />,
    },
    {
        key: 'settings',
        label: 'Settings',
        href: '/admin/settings',
        icon: <FaCogs />,
    },
    {
        key: 'policies',
        label: 'Policies',
        href: '/admin/policies',
        icon: <FaFileContract />,
    },
    {
        key: 'about-us',
        label: 'About Us',
        href: '/admin/about-us',
        icon: <FaInfoCircle />,
    },
    {
        key: 'contact-us',
        label: 'Contact Us',
        href: '/admin/contact-us',
        icon: <FaPhoneAlt />,
    },
];


// {
//     key: 'payments',
//     label: 'Payments',
//     href: '/admin/payments',
//     icon: <FaMoneyCheckAlt />,
// },
// {
//     key: 'app-releases',
//     label: 'App Releases',
//     href: '/admin/app-releases',
//     icon: <FaRocket />,
// },
// {
//     key: 'transactions',
//     label: 'Transactions',
//     href: '/admin/transactions',
//     icon: <FaExchangeAlt />,
// },


// {
//     key: 'coupons',
//     label: 'Coupons',
//     href: '/admin/coupons',
//     icon: <FaFileInvoiceDollar />,
// },
// {
//     key: 'design-studio',
//     label: 'Design Studio',
//     href: '/admin/design-studio',
//     icon: <FaPaintBrush />,
// },
// {
//     key: 'billing',
//     label: 'Billing',
//     href: '/admin/billing',
//     icon: <FaFileInvoiceDollar />,
// },